package com.example.autoecole.global

object SqlTable {
    const val admin = "CREATE TABLE ADMIN(ID INTEGER PRIMARY KEY AUTOINCREMENT,USER_NAME TEXT DEFAULT '',"+
            "PASSWORD TEXT DEFAULT '',MOBILE TEXT DEFAULT '')"
    const val student = "CREATE TABLE STUDENT(ID INTEGER PRIMARY KEY AUTOINCREMENT, FNAME TEXT,"+
            " SNAME TEXT, BIRTHDATE DATE, NATION TEXT, ADRESSE TEXT, PHONENUMBER INTEGER, EMAIL TEXT , FREE_PAID DECIMAL, MANQUE DECIMAL)"
    const val moniteur = "CREATE TABLE MONITEUR(ID INTEGER PRIMARY KEY AUTOINCREMENT, FNAME TEXT, SNAME TEXT, "+
            "BIRTHDATE DATE, NATION TEXT, ADRESSE TEXT, PHONENUMBER INTEGER, EMAIL TEXT,MATRICULE INTEGER ,MARQUE TEXT,TYPE TEXT)"
    const val paiement="CREATE TABLE PAIEMENT(PRIX_PERMIS DECIMAL  DEFAULT NULL)"
    const val session = "CREATE TABLE SESSION(ID INTEGER PRIMARY KEY AUTOINCREMENT, STUDENT_ID INTEGER, DATE TEXT, TIME TEXT,MONITEUR_ID INTEGER, PLACE TEXT, FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID), FOREIGN KEY (MONITEUR_ID) REFERENCES MONITEUR(ID))"


}